# Generated by Django 4.2.1 on 2023-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(blank=None, max_length=30, null=True),
        ),
    ]
