# Generated by Django 4.2.1 on 2023-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='otp',
            name='password2',
            field=models.CharField(blank=None, max_length=30, null=True),
        ),
    ]
