# Generated by Django 4.2.1 on 2023-07-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_password_otp_password1_otp_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
