# Generated by Django 4.2.1 on 2023-10-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
