# Generated by Django 4.2.1 on 2023-10-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_contactus_email_contactus_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status_see',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
