# Generated by Django 4.2.1 on 2023-10-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_contactus_status_see'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='username',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
