# Generated by Django 4.2.1 on 2023-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_contactus_username_contactus_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRestPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.SmallIntegerField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
