# Generated by Django 4.2.1 on 2023-11-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_otprestpassword_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprestpassword',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
