# Generated by Django 4.2.1 on 2023-11-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_otprestpassword_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprestpassword',
            name='phone',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
