# Generated by Django 4.2.1 on 2023-11-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_otprestpassword_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprestpassword',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otprestpassword',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otprestpassword',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='otprestpassword',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
